apiVersion : apps/v1
kind: Deployment
metadata:
  name: az1springbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: az1springbootapp
  template:
    metadata:
      labels:
        app: az1springbootapp 
    spec:
      containers:
        - name: az1springbootapp 
          image: myacrrepo431.azurecr.io/az1springbootapp
          ports:
          - containerPort: 80
